options(BioC_MIRROR = "http://bioconductor.statistik.tu-dortmund.de")
options(BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS = FALSE)
options(BIOCONDUCTOR_CONFIG_FILE = "C:/Program Files/R/R-4.2.2/etc/config.yaml")

install.packages("Package Name")

if(!require("BiocManager",quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("Package Name")

#setting up working directory
setwd("Z:/inbox/Alan")

#Necessary library 
library(ChIPseeker)
library(GenomicAlignments)
library(ReactomePA)
library(GenomicFeatures)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(GenomeInfoDb)
library(DESeq2)
library(ggplot2)
library(dplyr)
library(EnhancedVolcano)
library(pheatmap)
library(ggbeeswarm)
library(genefilter)
library(biomaRt)
library(tidyverse)
library(hrbrthemes)
library(tm)
library(proustr)
library(VennDiagram)
library(RColorBrewer)
library(ggrepel)
library(ggimage)
library(reshape2)
library(ggVennDiagram)
library(UpSetR)
library(viridis)
library(clusterProfiler)
library(org.Hs.eg.db)
library(ggupset)
library(enrichplot)
library(DOSE)
library(ggnewscale)
library(DEGreport)
library(AnnotationDbi)
library(GGally)
library(SummarizedExperiment)
library(tidyverse)
library(readr)
library(plyranges)
library(AnnotationHub)
library(ensembldb)
library(FindIT2)
library(biomaRt)
library(XGR)
library(EnsDb.Hsapiens.v86)
Txdb<-EnsDb.Hsapiens.v86
all_geneSet<- genes(Txdb)
library(SNPlocs.Hsapiens.dbSNP144.GRCh38)
snps<-SNPlocs.Hsapiens.dbSNP144.GRCh38